name: flywheel_carousel_example
description: Example app for flywheel_carousel.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.11.1
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flywheel_carousel:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
